### PR TITLE
Support hidden

### PR DESCRIPTION
**Pull request by willcharlton**
Can we just merge your branch to master? It doesn't look like dreamhost is going to be fixing this anytime soon. 

Thanks,

~Will

### CODE REVIEW

**Comment by electrofelix** [comment]
That doesn't really solve the problem where it's not available via pypi. I'll poke one of the people I know who worked at dreamhost and see if he can help either in getting the PR merged or transferring the project ownership.

I'll try to get an answer in the next week as the other solution is to push it up as  a different project to pypi

**Comment by willcharlton** [comment]
Good point - getting it on pypi is the real problem. I forked your work for the time being. Thanks for your work and let me know if there's anything I can help with!

**Comment by electrofelix** [comment]
@willcharlton good news, got some help to create a new org sphinxcontrib and the sphinxcontrib-fulltoc project was moved to it, so expect to merge it today and will look at a new release at the start of next week (need to check if there is anything else to be tested).

**Comment by electrofelix** [comment]
Going to close this for now in favour of landing the existing PR on sphinxcontrib/sphinxcontrib-fulltoc#12 and we should also be able to release that to PyPi

**Pull request closed without merging**
